name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: deps
      run: sudo apt-get install -y libusb-dev libusb-1.0-0-dev build-essential ffmpeg
    - name: make
      run: make
