name: Publish Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: deps
      run: sudo apt-get install -y libusb-dev libusb-1.0-0-dev build-essential ffmpeg
    - name: make
      run: make
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: publish
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Build @ ${{ steps.vars.outputs.sha_short }}"
        files: |
          fpv-video-out

